package abstractExercise;

public enum ActionCategory {

    MODIFICACARRELLO,
    ACQUISTACARRELLO,
    CAMBIAPASSWORD,

    MODIFICAINFOPRODOTTO,
    MODIFICACATEGORIAPRODOTTO,
    MODIFICAUTENTESTANDARD,
    BANUSER,

    MODIFICATEMPLATEPAGINAPRODOTTO,
    METTISITOINMANUTENZIONE,
    MODIFICAUTENTEAMMNISTRATORE

}
